name: IIIT Notebook
collections:
    courses:
      output: true

defaults:
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
